name: Java CI with Gradle

on:
  push:
    branches: [ "master", "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Build and measure coverage
      shell: bash
      run: |
        chmod +x gradlew
        if [ "$RUNNER_OS" == "Linux" ]; then
          xvfb-run --auto-servernum ./gradlew build jacocoTestReport --no-daemon --info
        else
          ./gradlew build jacocoTestReport --no-daemon --info
        fi

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report-${{ matrix.os }}
        path: |
            core/build/reports/checkstyle/
            headless/build/reports/checkstyle/
            lwjgl3/build/reports/checkstyle/
        retention-days: 7

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-${{ matrix.os }}
        path: headless/build/reports/jacoco/test/html/
        retention-days: 7

    - name: Create distribution JAR
      shell: bash
      run: ./gradlew lwjgl3:dist --no-daemon

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-${{ matrix.os }}
        path: lwjgl3/build/libs/*.jar
        retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          game-ubuntu-latest.jar/*
          game-windows-latest.jar/*
          game-macos-latest.jar/*
